---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: {{appname}}
  name: {{appname}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: {{appname}}
    spec:
      containers:
        - name: {{appname}}
          image: {{image}}
          command:
            - ./run-server.sh
          ports:
            - name: {{appname}}
              protocol: TCP
              containerPort: 5000
          env:
            - name: CELERY_BACKEND
              value: {{celery_backend}}
            - name: CELERY_BROKER
              value: {{celery_broker}}
            - name: GITLAB_USER
              value: {{gitlab_user}}
            - name: GITLAB_TOKEN
              value: {{gitlab_token}}
            - name: GITHUB_CONTEXT
              value: {{github_context}}
            - name: GITLAB_API
              value: "https://gitlab.com"
            - name: FAILFASTCI_NAMESPACE
              value: {{gitlab_namespace}}
            - name: GITHUB_INTEGRATION_PEM
              valueFrom:
                secretKeyRef:
                  name: {{appname}}
                  key: integration_pem
            - name: GITHUB_INTEGRATION_ID
              value: "{{integration_id}}"
          livenessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 30
