---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: {{appname}}
  name: {{appname}}
spec:
  type: {{svc_type}}
  ports:
    - port: 5000
      targetPort: 5000
      name: {{appname}}
    - port: 5555
      targetPort: 5555
      name: flower
  selector:
    k8s-app: {{appname}}
