---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: {{appname}}
  name: {{appname}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: {{appname}}
    spec:
      containers:
        - name: {{appname}}
          image: {{image}}
          imagePullPolicy: Always
          command:
            - gunicorn
            - hub2labhook.api.wsgi:app
            - -b
            - :5000
            - --timeout
            - "120"
            - -w
            - "4"
            - "--reload"
          ports:
            - name: {{appname}}
              protocol: TCP
              containerPort: 5000
          env:
            - name: GITLAB_TRIGGER
              value: {{trigger}}
            - name: GITLAB_REPO
              value: {{repo}}
            - name: GITLAB_TOKEN
              value: {{token}}
            - name: GITHUB_CONTEXT
              value: 'gitlab-ci'
            - name: GITHUB_INTEGRATION_PEM
              value: {{integration_pem}}
            - name: GITHUB_INTEGRATION_ID
              value: "{{integration_id}}"
            - name: GITHUB_INSTALLATION_ID
              value: "{{installation_id}}"
          livenessProbe:
            httpGet:
              path: /version
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 30
